### PR TITLE
rpc: Add structured querying for event subscriptions

### PR DESCRIPTION
**Pull request by thanethomson**
Partially addresses #582.

This PR adds structured querying to RPC event subscription, which replaces the `String`-based interface for subscription.

No query parsing is implemented yet, as it's not clear yet whether we need it at the moment and we need to figure out how to translate the [query PEG](https://github.com/tendermint/tendermint/blob/master/libs/pubsub/query/query.peg) from the Go version of Tendermint.

* [x] Referenced an issue explaining the need for the change
* [x] Updated all relevant documentation in docs
* [x] Updated all code comments where relevant
* [x] Wrote tests
* [x] Updated CHANGELOG.md

### CODE REVIEW

**Comment by romac** [comment]
@thanethomson Great stuff!

I took the liberty pushing a few non-controversial changes (imho):

- Add missing doc comments to some methods of `Query` (27f2de9ecfc1761bbfc2d335c5ff0ce1204d0475)
- Use `Display` instead of `ToString` to pretty-print queries, which is [more](https://doc.rust-lang.org/std/string/trait.ToString.html) [idiomatic](https://stackoverflow.com/a/27770058) (568abaf)
- Impement `From` instead of `Into` for `Operand`, which again is [more idiomatic](https://doc.rust-lang.org/std/convert/trait.Into.html) (345f281)

The last commit (27fe514) merges the `Operation` and `Condition` structs together, which I personally find simpler even though it distributes the key into each variant of the enum. I don't feel strongly about this and only did this as a suggestion so let me know if you'd rather keep the original version and I'll revert the commit.

**Comment by romac** [comment]
Looks like the build [is failing on Nightly](https://github.com/informalsystems/tendermint-rs/runs/1219272754).

```
2020-10-07T08:16:01.4214668Z    Compiling ecdsa v0.8.3
2020-10-07T08:16:01.8028615Z error[E0277]: cannot multiply `&NonZeroScalar<C>` to `<C as ProjectiveArithmetic>::ProjectivePoint`
2020-10-07T08:16:01.8035228Z ##[error]  --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/ecdsa-0.8.3/src/sign.rs:90:58
2020-10-07T08:16:01.8043918Z    |
2020-10-07T08:16:01.8044748Z 90 |             public_key: (C::ProjectivePoint::generator() * &self.secret_scalar).to_affine(),
2020-10-07T08:16:01.8045596Z    |                                                          ^ no implementation for `<C as ProjectiveArithmetic>::ProjectivePoint * &NonZeroScalar<C>`
2020-10-07T08:16:01.8046174Z    |
2020-10-07T08:16:01.8046773Z    = help: the trait `Mul<&NonZeroScalar<C>>` is not implemented for `<C as ProjectiveArithmetic>::ProjectivePoint`
2020-10-07T08:16:01.8047526Z help: consider further restricting the associated type
2020-10-07T08:16:01.8047864Z    |
2020-10-07T08:16:01.8048427Z 87 |         AffinePoint<C>: Clone + Debug, <C as ProjectiveArithmetic>::ProjectivePoint: Mul<&NonZeroScalar<C>>
2020-10-07T08:16:01.8049018Z    |                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2020-10-07T08:16:01.8049204Z 
2020-10-07T08:16:01.8476530Z error: aborting due to previous error
2020-10-07T08:16:01.8477619Z ##[error]aborting due to previous error
2020-10-07T08:16:01.8479396Z For more information about this error, try `rustc --explain E0277`.
2020-10-07T08:16:01.8636042Z error: could not compile `ecdsa`
```

**Comment by thanethomson** [comment]
Excellent, thanks @romac! Looks great - I like the simplification 👍

Are there any clippy lints we can enable that can warn us about there being more idiomatic ways to implement specific pieces of code?

**Comment by romac** [comment]
Not to my knowledge. Closest lint I could find is https://rust-lang.github.io/rust-clippy/master/#inherent_to_string but it would not have helped in this case.

I guess there are valid use cases for implementing ToString or defining a From instance directly which is why Clippy does not warn about that, or perhaps those lints are just currently missing.

**Review by romac — APPROVED** [review]

**Comment by tony-iqlusion** [comment]
My best guess for the `ecdsa` breakage on nightly is something broken with `Deref` rules.

I can try to repro it locally and see if there's a quick fix to work around the issue. This might also be worth reporting upstream.

**Comment by tony-iqlusion** [comment]
Plausible cause of the nightly regression: https://github.com/rust-lang/rust/issues/77638

**Pull request merged**
