### PR TITLE
Make crypto implementations replaceable

### PR DESCRIPTION
**Pull request by mzabaluev**
Resolves: #1213

I took some of the changes from #1214 and made more extensive use of them in tendermint hashing.

* [x] Referenced an issue explaining the need for the change
* [ ] Updated all relevant documentation in docs
* [x] Updated all code comments where relevant
* [x] Wrote tests
* [x] Added entry in `.changelog/`

### CODE REVIEW

**Comment by mzabaluev** [comment]
Minimized the failing `corrupted_hash` test to this input:
```
tc = TestCase { length: 2, chain: LightChain { info: Info { id: chain::Id(test-chain), height: block::Height(2), last_block_id: Some(Id { hash: Hash::Sha256(1843C619BB7E92A4D6420B0A2A2774D478613D5FBDAAB1D981720D4DA71B1270), part_set_header: Header { total: 0, hash: Hash::None } }), time: None }, light_blocks: [LightBlock { header: Some(Header { validators: Some([Validator { id: Some("1"), voting_power: Some(50), proposer_priority: None }, Validator { id: Some("2"), voting_power: Some(50), proposer_priority: None }]), next_validators: Some([Validator { id: Some("1"), voting_power: Some(50), proposer_priority: None }, Validator { id: Some("2"), voting_power: Some(50), proposer_priority: None }]), chain_id: Some("test-chain"), height: Some(1), time: Some(Time(2021-01-08 11:23:41.0)), proposer: None, last_block_id_hash: None }), commit: Some(Commit { header: Some(Header { validators: Some([Validator { id: Some("1"), voting_power: Some(50), proposer_priority: None }, Validator { id: Some("2"), voting_power: Some(50), proposer_priority: None }]), next_validators: Some([Validator { id: Some("1"), voting_power: Some(50), proposer_priority: None }, Validator { id: Some("2"), voting_power: Some(50), proposer_priority: None }]), chain_id: Some("test-chain"), height: Some(1), time: Some(Time(1970-01-01 0:00:01.0)), proposer: None, last_block_id_hash: None }), votes: Some([Vote { validator: Some(Validator { id: Some("1"), voting_power: Some(50), proposer_priority: None }), index: Some(0), header: Some(Header { validators: Some([Validator { id: Some("1"), voting_power: Some(50), proposer_priority: None }, Validator { id: Some("2"), voting_power: Some(50), proposer_priority: None }]), next_validators: Some([Validator { id: Some("1"), voting_power: Some(50), proposer_priority: None }, Validator { id: Some("2"), voting_power: Some(50), proposer_priority: None }]), chain_id: Some("test-chain"), height: Some(1), time: Some(Time(1970-01-01 0:00:01.0)), proposer: None, last_block_id_hash: None }), prevote: None, height: None, time: None, round: Some(1), nil: None }, Vote { validator: Some(Validator { id: Some("2"), voting_power: Some(50), proposer_priority: None }), index: Some(1), header: Some(Header { validators: Some([Validator { id: Some("1"), voting_power: Some(50), proposer_priority: None }, Validator { id: Some("2"), voting_power: Some(50), proposer_priority: None }]), next_validators: Some([Validator { id: Some("1"), voting_power: Some(50), proposer_priority: None }, Validator { id: Some("2"), voting_power: Some(50), proposer_priority: None }]), chain_id: Some("test-chain"), height: Some(1), time: Some(Time(1970-01-01 0:00:01.0)), proposer: None, last_block_id_hash: None }), prevote: None, height: None, time: None, round: Some(1), nil: None }]), round: Some(1) }), validators: Some([Validator { id: Some("1"), voting_power: Some(50), proposer_priority: None }, Validator { id: Some("2"), voting_power: Some(50), proposer_priority: None }]), next_validators: Some([Validator { id: Some("1"), voting_power: Some(50), proposer_priority: None }, Validator { id: Some("2"), voting_power: Some(50), proposer_priority: None }]), provider: Some(node::Id(badfadad0befeedc0c0adeadbeefc0ffeefacade)) }, LightBlock { header: Some(Header { validators: Some([Validator { id: Some("1"), voting_power: Some(50), proposer_priority: None }, Validator { id: Some("2"), voting_power: Some(50), proposer_priority: None }]), next_validators: Some([Validator { id: Some("1"), voting_power: Some(50), proposer_priority: None }, Validator { id: Some("2"), voting_power: Some(50), proposer_priority: None }]), chain_id: Some("test-chain"), height: Some(2), time: Some(Time(1970-01-01 0:00:02.0)), proposer: None, last_block_id_hash: Some(Hash::Sha256(BD301C7EC29BF24128086A09928F6582A69ED4DFA105D30B56E85F0661DC0C43)) }), commit: Some(Commit { header: Some(Header { validators: Some([Validator { id: Some("1"), voting_power: Some(50), proposer_priority: None }, Validator { id: Some("2"), voting_power: Some(50), proposer_priority: None }]), next_validators: Some([Validator { id: Some("1"), voting_power: Some(50), proposer_priority: None }, Validator { id: Some("2"), voting_power: Some(50), proposer_priority: None }]), chain_id: Some("test-chain"), height: Some(2), time: Some(Time(1970-01-01 0:00:02.0)), proposer: None, last_block_id_hash: Some(Hash::Sha256(BD301C7EC29BF24128086A09928F6582A69ED4DFA105D30B56E85F0661DC0C43)) }), votes: Some([Vote { validator: Some(Validator { id: Some("1"), voting_power: Some(50), proposer_priority: None }), index: Some(0), header: Some(Header { validators: Some([Validator { id: Some("1"), voting_power: Some(50), proposer_priority: None }, Validator { id: Some("2"), voting_power: Some(50), proposer_priority: None }]), next_validators: Some([Validator { id: Some("1"), voting_power: Some(50), proposer_priority: None }, Validator { id: Some("2"), voting_power: Some(50), proposer_priority: None }]), chain_id: Some("test-chain"), height: Some(2), time: Some(Time(1970-01-01 0:00:02.0)), proposer: None, last_block_id_hash: Some(Hash::Sha256(BD301C7EC29BF24128086A09928F6582A69ED4DFA105D30B56E85F0661DC0C43)) }), prevote: None, height: None, time: None, round: Some(1), nil: None }, Vote { validator: Some(Validator { id: Some("2"), voting_power: Some(50), proposer_priority: None }), index: Some(1), header: Some(Header { validators: Some([Validator { id: Some("1"), voting_power: Some(50), proposer_priority: None }, Validator { id: Some("2"), voting_power: Some(50), proposer_priority: None }]), next_validators: Some([Validator { id: Some("1"), voting_power: Some(50), proposer_priority: None }, Validator { id: Some("2"), voting_power: Some(50), proposer_priority: None }]), chain_id: Some("test-chain"), height: Some(2), time: Some(Time(1970-01-01 0:00:02.0)), proposer: None, last_block_id_hash: Some(Hash::Sha256(BD301C7EC29BF24128086A09928F6582A69ED4DFA105D30B56E85F0661DC0C43)) }), prevote: None, height: None, time: None, round: Some(1), nil: None }]), round: Some(1) }), validators: Some([Validator { id: Some("1"), voting_power: Some(50), proposer_priority: None }, Validator { id: Some("2"), voting_power: Some(50), proposer_priority: None }]), next_validators: Some([Validator { id: Some("1"), voting_power: Some(50), proposer_priority: None }, Validator { id: Some("2"), voting_power: Some(50), proposer_priority: None }]), provider: Some(node::Id(badfadad0befeedc0c0adeadbeefc0ffeefacade)) }] }, target_height: block::Height(1), trusted_height: block::Height(2) }
```

**Comment by Farhad-Shabani** [comment]
I have been reviewing the changes, some thoughts came to my mind, don’t know how much is applicable:

- It seems that `CryptoProvider` should be implemented as a higher-level trait making hashing/Verification/Signing operations available all over the repo. while this way it already is fed upward from a struct, so it's making us introduce PhantomData & generic types to funcs
- `CryptoProvider` already hosts incongruous types for different functionalities. These purposes can be decoupled, having them within multiple smaller traits. So it would get more manageable & modular for other possible future calls
- Some types could be named more generic

**Therefore, e.g.:** 

```rust
pub trait HashProvider: Default + Send + Sync {
	// Using `Hash` instead of `Sha256` as it might accept other hashing algorithms
	// Though, I noticed we also have `Hash` types in other places like:
	// `tendermint/hash.rs` and `tendermint/merkle.rs` don't know if these could be integrated
	type Hash: Digest<OutputSize = U32> + FixedOutputReset;
	type Hasher: Hasher<Self::Hash>

pub trait Hasher<H: HashProvider> {
	fn hasher(&self, hash: &H) -> Result<[u8; 32], Error>;

use signature::{Signature, Signer, Verifier};
pub trait SignatureProvider: Default + Send + Sync {
        // Using `Signature` instead of `EcdsaSecp256k1Signature` to not be curve specific
        type Signature: Signature;
        type Signer: Signer<Self::Signature>;
        type Verifier: Verifier<Self::Signature>;
}
```

 - Accordingly, we might be able to pass our current functions as default implementations(behaviors) of Hasher/Verifier/Signer traits rather than having them through `feature="rust-crypto"`. Also, implementing the `Hasher` trait on the `Header` and `Set` structs will give us the `hasher()` method we need.

- Another thing, I don’t know if we can refactor `merkle.rs`  and have `simple_hash_from_byte_vectors` within a trait (name it e.g. HashTree), So we could accept various hashing tree logics and bound it by`HashProvider`
```rust
pub trait HashTree: HashProvider {
        fn simple_hash_from_byte_vectors(&self, byte_vecs: &[Vec<u8>]) -> Hash
}
```

**Comment by mzabaluev** [comment]
> It seems that `CryptoProvider` should be implemented as a higher-level trait making hashing/Verification/Signing operations available all over the repo. while this way it already is fed upward from a struct, so it's making us introduce PhantomData & generic types to funcs

In this PR I actually managed to avoid introducing `PhantomData`, except where it was already present in the fake-Substrate verifier test created in #1214.

>     * `CryptoProvider` already hosts incongruous types for different functionalities. These purposes can be decoupled, having them within multiple smaller traits. So it would get more manageable & modular for other possible future calls

I like it, this continues breaking down of `HostProvider` into more sensible chunks, and I already see most of `CryptoProvider` is not needed in places that only care about hashing. Maybe even different signature algo providers could have each its own trait. Basically, if the need for a unified trait is not evident from usage, it can be split up.

> ```rust
> 
> pub trait Hasher<H: HashProvider> {
> 	fn hasher(&self, hash: &H) -> Result<[u8; 32], Error>;
> }
> ```

From the name it's not very clear what does this trait do. In other crypto code, the term "hasher" is typically used for the digest state objects, but here it looks like it's meant for hashing `self` with the provided instance of a crypto provider.
Note that the current `CryptoProvider` trait is instanceless, because it's the associated types that it references that implement instanced digest APIs.

To think of it a bit more, maybe we just want to put more specialized and domain-friendly faces on top of `Digest` and `Signature` with blanket-implemented traits?

> Accordingly, we might be able to pass our current functions as default implementations(behaviors) of Hasher/Verifier/Signer traits rather than having them through `feature="rust-crypto"`. Also, implementing the `Hasher` trait on the `Header` and `Set` structs will give us the `hasher()` method we need.

So it's actually a "hash-me" trait.
I don't see a need for a trait that generalizes over `Header` and `validator::Set`, I think inherent methods would do the job.

> Another thing, I don’t know if we can refactor `merkle.rs`  and have `simple_hash_from_byte_vectors` within a trait (name it e.g. HashTree), So we could accept various hashing tree logics and bound it by`HashProvider`
> 
> 
> ```rust
> pub trait HashTree: HashProvider {
>         fn simple_hash_from_byte_vectors(&self, byte_vecs: &[Vec<u8>]) -> Hash
> }
> ```

I would not couple hashing strategies in one trait hierarchy with the hashing provider, it seems to me like they could be implemented orthogonally. Alternative hashing strategies seem like YAGNI for the purposes of this change, so I'd put it off to a later redesign.

**Comment by Farhad-Shabani** [comment]
> but here it looks like it's meant for hashing `self`with the provided instance of a crypto provider. 
> So it's actually a "hash-me" trait.

I meant so. And actually, having one of `fn hash_me()` or `type Hash: Sha256` under `HashProvider` trait would suffice to traverse the merkle hashing tree with the desired hash function. Unless we want to have simultaneous access to different hashing funcs at once which I don't think to be the case

> To think of it a bit more, maybe we just want to put more specialized and domain-friendly faces on top of Digest and Signature with blanket-implemented traits?

This could be a good idea

> I would not couple hashing strategies in one trait hierarchy with the hashing provider, it seems to me like they could be implemented orthogonally. Alternative hashing strategies seem like YAGNI for the purposes of this change, so I'd put it off to a later redesign.

Agree, it could be the subject of future work if necessary

**Comment by mzabaluev** [comment]
Looks much better now, let's see if we can make it work.

**Comment by mzabaluev** [comment]
@Farhad-Shabani
> Another thing, I don’t know if we can refactor `merkle.rs`  and have `simple_hash_from_byte_vectors` within a trait (name it e.g. HashTree), So we could accept various hashing tree logics and bound it by `HashProvider`

It ended up a bit more loosely bound, but indeed there is now a `MerkleHash` trait, with implementations that can make use of a host-provided function, or an incremental `Digest + FixedOutputReset` SHA256 implementation.

**Comment by Farhad-Shabani** [comment]
I liked the generic interface over the Merkle tree :+1: 

While reviewing, I came up with some design tweaks. I worked on them in a [separate branch](https://github.com/informalsystems/tendermint-rs/pull/1252) just to see how much would apply and serve as a reference to better convey my purposes.

Luckily, they worked, particularly around the domains we've been concerned with. But I don't know if they have any implications beyond the scope of this PR. Please tell me @mzabaluev if there is. Here are the the suggestions:

- The hierarchy of hashing-related traits can be modified as follows, so each element will only access the required interfaces, I am picking hierarchical design, as I think it covers the necessary generic interface (In very rare cases, you may need orthogonal design, so enable you to use more than one Merkle hasher in a blockchain)
    1. A high-level `HashType` trait and and as a bound for `Sha256` trait, responsible for feeding required hashing function for `id.rs` and `account.rs` and to make `sha2::Sha256` accessible for internal use of `Sha256` trait
    
    ```rust
    pub trait HashType {
        type Hash: Send + Sync;
    }
    ```
    
    2. Then, the `Sha256` trait can come with a default impl to add digesting interface needed by the Merkle tree
    
    ```rust
    pub trait Sha256: HashType {
        fn digest_sha256(data: impl AsRef<[u8]>) -> [u8; HASH_SIZE] {
    	    //default implementation
        }
    }
    ```
    
    3. Lastly `MerkleHash`. Here a default impl could suffice, particularly, if the incremental one does not buy much for us. so we can keep the codes lighter. 
    We also can move `simple_hash_from_byte_vectors` (So, not needed to pass generic type `H`anymore) under the `MerkleHash` trait to make it a comprehensive interface
    
    ```rust
    pub trait MerkleHash: DigestSha256 {
        fn empty_hash(&mut self) -> Hash {
    		// default implementation
        }
    
        fn leaf_hash(&mut self, bytes: &[u8]) -> Hash {
    		// default implementation
        }
        fn inner_hash(&mut self, left: Hash, right: Hash) -> Hash {
    		// default implementation
        }
    
        fn hash_byte_vectors(&mut self, byte_vecs: &[Vec<u8>]) -> Hash {
    		// default implementation
        }
    
        fn simple_hash_from_byte_vectors(&mut self, byte_vecs: &[Vec<u8>]) -> Hash {
            self.hash_byte_vectors(byte_vecs)
        }
    }
    ```
    
- following that, we can have default (tendermint-specific) instances for `Sha256` and `MerkleHash` call it `DefaultSha256` and `DefaultMerkleHash`. This way we provide both needed implementations and interfaces without `feature="rust-crypto"`

**Comment by Wizdave97** [comment]
> 

This would work for us as long as the SignatureType and SignatureVerifier implementation can be modified when we pull in `tendermint-rs`

**Comment by romac** [comment]
FYI the `signature` crate just released a new major version, might be worth taking a look at the changes: https://github.com/RustCrypto/traits/blob/master/signature/CHANGELOG.md

**Comment by mzabaluev** [comment]
> FYI the `signature` crate just released a new major version

We should update to it after ed25519-consensus and other crates release their updates using the same version.
As of now, we should provide our own trait because Henry's crate does not actually use `signature` due to some technical issues with the old framework version.

**Comment by romac** [comment]
> We should update to it after ed25519-consensus and other crates release their updates using the same version.

Do you have a list of all the crates we need to wait on?

**Comment by mzabaluev** [comment]
> Do you have a list of all the crates we need to wait on?

Not in this PR, but here's a brief survey of the dependency tree:

* `ed25519` (the framework lib, no implementation) - had a 2.0 release recently.
* `ecdsa` - 0.15 release has been updated.
* `ed25519-consensus` will probably need to be adapted to use the new framework crates, to spare us the need to define our own abstraction traits.

**Comment by tony-iqlusion** [comment]
`ed25519-consensus` doesn't impl the `signature` crate's traits, although I have a half-finished PR open:

https://github.com/penumbra-zone/ed25519-consensus/pull/6

**Comment by mzabaluev** [comment]
> `ed25519-consensus` doesn't impl the `signature` crate's traits, although I have a half-finished PR open:

@tony-iqlusion Now that the warts in `signature` preventing an efficient curve point backed implementation have been reportedly resolved in 2.0, can this be completed?

**Comment by blasrodri** [comment]
Really appreciate this!!

**Comment by blasrodri** [comment]
@Farhad-Shabani can you please review this PR? We really need it merged :)

**Comment by romac** [comment]
@Farhad-Shabani I approved the PR and merged main in. Feel free to merge this!

**Comment by Farhad-Shabani** [comment]
Thank you so much @mzabaluev, I truly appreciate your patience. And thank you @romac for reviewing it 🙏🏻 
:tada: :tada: :tada:

**Pull request merged**
