### PR TITLE
fix(rpc): `validator_updates` in block results might be explicit null

### PR DESCRIPTION
**Pull request by xoac**
* [ ] Referenced an issue explaining the need for the change
* [X] Updated all relevant documentation in docs
* [X] Updated all code comments where relevant
* [ ] Wrote tests
* [x] Added entry in `.changelog/`

### CODE REVIEW

**Review by mzabaluev — CHANGES_REQUESTED** [review]
It seems that the change does not match the title of the pull request. `validator_updates` is a field in `ResponseEndBlock`, isn't it?

Can you file an issue detailing the problem?

Also, it would be good to provide a test fixture, hopefully one obtained from a real-world node setup.

**Comment by xoac** [comment]
@mzabaluev replaced this one with #1318 as the issue  was that HttpClient ignore compact node when query v0.34 last block results. 

I think this PR is also valid as `value` in `EventAttribute` can be explicitly null.

**Comment by mzabaluev** [comment]
> I think this PR is also valid as value in EventAttribute can be explicitly null.

I have not observed that with 0.37 yet, and I believe the serialization code in CometBFT has been changed to not produce null values. The 0.34 dialect deserialization does allow null, though. Can you provide an example where a null value is produced?

**Comment by xoac** [comment]
Probably my wrong assumption. For now I query only version 0.34

**Pull request closed without merging**
