### PR TITLE
Model-based tests for LightClient

### PR DESCRIPTION
**Pull request by andrey-kuprianov**
Part 6 of #529. See also #414. This PR adds some auto-generated static LightClient tests.

* [X] Referenced an issue explaining the need for the change
* [X] Updated all relevant documentation in docs
* [X] Updated all code comments where relevant
* [x] Wrote tests
* [x] Updated CHANGELOG.md

### CODE REVIEW

**Comment by shonfeder** [comment]
iiuc, since this is auto generated, it should be good to go since all the pre-reqs are merged?

**Review by shonfeder — DISMISSED** [review]

**Comment by andrey-kuprianov** [comment]
Please do not merge this PR yet. There are two reasons:
- the current tests on master are failing, so it's better to wait till those run again.
- I will extend this PR with more TLA+ and generated tests.

**Comment by melekes** [comment]
> Please do not merge this PR yet. There are two reasons:
> 
>     * the current tests on master are failing, so it's better to wait till those run again.
> 
>     * I will extend this PR with more TLA+ and generated tests.

hint: you can convert your PR to draft to avoid it getting accidentally merged 
image

**Review by romac — APPROVED** [review]
LGTM (can't really speak for the TLA ones but I'll trust you on that :))

**Pull request merged**
