### PR TITLE
Temporary fix to unblock MBT in go

### LINKED ISSUE #633: Enable MBT for LightClient in Tendermint-go
There is already plenty of work done by @melekes in the Tendermint-go repository to integrate our LightClient MBT tests.
See this [issue](https://github.com/tendermint/tendermint/issues/5322) and this [PR](https://github.com/tendermint/tendermint/pull/5461). The current state is that the validation of headers doesn't pass the checks in [block.go](https://github.com/tendermint/tendermint/blob/260cc5dd698941a794cac00652ff06f71a8b9667/types/block.go#L50).

We need to extend the Testgen such that it generates all the necessary fields, and makes the above PR to work. Also things like the [block version](https://github.com/tendermint/tendermint/pull/5461/commits/fac95b0bd50d662c20ac4f705d20ede79ada657f) should be generated automatically.

The workflow for this issue is approximately as follows:
 1. extend Testgen to generate all necessary fields
 2. regenerate the static MBT files
 3. put them locally into the branch of the above PR, and try to execute the test driver
 4. repeat 1-3 until either the tests pass, or some problem in the Go test driver is discovered. In the latter case either try to fix it, or consult with @melekes.

### PR DESCRIPTION
**Pull request by Shivani912**
closes #633 

**Summary of changes:**
- initialized `PartsSetHeader` with some value instead of `PartsSetHeader::default()` - see #645 
- `Version.block` set to 11 for compatibility because tendermint-go is hardcoded to work with block version at 11
- ~~Re-generated MBT test files with the above mentioned changes~~ This already landed in master with #648

* [X] Referenced an issue explaining the need for the change
* [ ] Updated all relevant documentation in docs
* [ ] Updated all code comments where relevant
* [ ] Wrote tests
* [ ] Updated CHANGELOG.md

### CODE REVIEW

**Review by andrey-kuprianov — DISMISSED** [review]
Looks good to me! Thanks for taking care of that, @Shivani912 :)

**Comment by melekes** [comment]
thanks @Shivani912! almost got it working 🏃  could you also rename `parts` to `part_set_header` within `block_id`? https://github.com/tendermint/tendermint/pull/5523

**Review by melekes — APPROVED** [review]
❤️

**Comment by Shivani912** [comment]
> thanks @Shivani912! almost got mbt in Go working 🏃 could you also rename `parts` to `part_set_header` within `block_id`? [tendermint/tendermint#5523](https://github.com/tendermint/tendermint/pull/5523)

Yes, I'm on it :)

**Comment by melekes** [comment]
I changed it locally. No need to do it here. Although you'll need to update it some time anyway.

**Review by andrey-kuprianov — APPROVED** [review]
Looks good, thanks:)

**Pull request merged**
