### PR TITLE
JSON test structure changes

### LINKED ISSUE #266: Conformance tests compatibility issues
**Context**
- Rust implementation is incompatible with Go implementation. 
- Details: Issues #260 and #259 

**Problem**
Since the conformance tests (JSON-based tests) are generated using the Go implementation, these incompatibilities make four of the `Commit` tests fail on deserialization. These are:
- one-third vals don't sign (both under single-step sequential and skipping)
- more than two-third vals did sign (both under single-step sequential and skipping)

**Proposed Solution**
After a good discussion with @greg-szabo and @Liamsi on this, it was decided to identify and run these tests separately where we let it fail on deserialization for now with an added warning about the issues around it. 
This way, we wouldn't have to makes changes to our code that are not acceptable i.e. accept an `AbsentCommitSig` without `ValidatorAddress` in this case. Also, once the issue is fixed on the Go implementation side, we'll be able to run these tests normally.

### PR DESCRIPTION
**Pull request by Shivani912**
closes #266 

To make identifying each test case easy, I've split up the test files and changed the directory structure. Now, each JSON file is a single test case.

**Directory Structure**
Under tendermint-rs/tendermint/tests/support/lite:

The four failing tests are found here:
1. ./single_step/sequential/commit/one_third_vals_don't_sign.json
2. ./single_step/sequential/commit/more_than_two_third_vals_sign.json
3. ./single_step/skipping/commit/one_third_vals_dont_sign.json
4. ./single_step/skipping/commit/more_than_two_third_vals_sign.json

**Further changes required:**
Issue #268 
* [x] Referenced an issue explaining the need for the change
* [ ] Updated all relevant documentation in docs
* [ ] Updated all code comments where relevant
* [ ] Wrote tests
* [ ] Updated CHANGES.md

### CODE REVIEW

**Comment by Shivani912** [comment]
> Thanks @Shivani912!
> 
> Looks like there are several places where the renamings were not reflected in the test code:
> 
> ```
> failures:
>     bisection_happy_path
>     bisection_header_out_of_trusting_period
>     bisection_invalid_validator_set
>     bisection_not_enough_commits
>     bisection_worst_case
>     commit_tests_verify
>     header_tests_verify
>     single_skip_commit_tests_verify
>     single_skip_val_set_tests_verify
>     val_set_tests_verify
> ```
> 
> All these complain about file or directory not found.

@Liamsi Yes, that's right. I summarized it in issue #268 about the changes we'll need to make in our test code.

**Comment by Liamsi** [comment]
Oh, should have read that first. Thanks, good work!

**Comment by Liamsi** [comment]
Interestingly, some other tests seem to fail here too:
```
Running file: "./tests/support/lite/bisection/multi_peer/conflicting_headers.json"
Case: Trusted height=1, bisecting to verify height=5 and receives a conflicting header from witness, should expect error
requested signed header for height:1
requested validators for height:2
requested signed header for height:5
requested validators for height:5
requested validators for height:6
requested signed header for height:5
requested validators for height:6

expected # bisections
Expected :2
Actual   :1
```

**Comment by Liamsi** [comment]
closing as this is superseded by #273 now.

**Pull request closed without merging**
