### PR TITLE
Adds more verification tests

### LINKED ISSUE #330: [light-client] Verification Testing
part of #320

The verifier is composed of multiple predicates, each of which should be tested for both the positive and negative case using concrete types. operations should be mocked out.

* validator_sets_match
* next_validators_match
* header_matches_commit
* valid_commit
* is_within_trust_period
* is_monotonic_bft_time
* is_monotonic_height
* has_sufficient_voting_power (related #235)
* has_sufficient_validators_overlap
* has_sufficient_signers_overlap
* valid_next_validator_set

Setup a simple test harness which facilitates to construction of concrete types to limit the dependency graph and make room for more general constructions.

### PR DESCRIPTION
**Pull request by Shivani912**
Closes #330 - I think we should close this one now as all of the predicates are being tested by conformance tests. We can open a separate issue for the lack of unit tests for these.

* [X] Referenced an issue explaining the need for the change
* [X] Updated all relevant documentation in docs
* [X] Updated all code comments where relevant
* [ ] Wrote tests
* [ ] Updated CHANGES.md

### CODE REVIEW

**Comment by romac** [comment]
I guess this depends on #474?

**Comment by Shivani912** [comment]
> I guess this depends on #474?

Yes :)



> Looks great, thanks a lot @Shivani912! Let's merge this after #474

Thanks for an early review @romac ! Will do...

**Comment by romac** [comment]
@Shivani912 Any idea why the `single_step_skipping` test is failing now?

**Comment by Shivani912** [comment]
> @Shivani912 Any idea why the `single_step_skipping` test is failing now?

Aha, the older tests (`tendermint/tests/lite.rs`) is failing because we haven't fixed the predicate issue there. I had in mind that it's already deprecated. Are we still maintaining that code? @romac

**Comment by romac** [comment]
Right, this is an old test, my bad! No we don't maintain that code anymore so I guess it's fine to just comment it out until we remove that code altogether.

**Comment by Shivani912** [comment]
Thank you @romac for actively reviewing this PR, appreciate it! I have addressed all your comments and I think it's ready to merge now. Will be great if you could approve it to be able to merge. Thanks again !

**Comment by romac** [comment]
Great stuff, thanks @Shivani912!

**Comment by ebuchman** [comment]
Aren't all these tests being added in the old `lite` pkg? Do those files get run from the new `light-client`? It looks like they're duplicated in both the old and the new test dirs?

Also, is there some way to see the mapping between the tests we have and the predicates? Like how should someone verify that there's a positive and negative test for each predicate?

**Pull request merged**
