### PR TITLE
Re-built tendermint-proto with serialization annotations

### LINKED ISSUE #634: Domain Type implementations needed by IBC
Following domain types and `TryFrom/ From` implementations are needed for (de)serialization of client IBC messages:

`tendermint_proto::types::SignedHeader` <===> `tendermint::block::signed_header::SignedHeader`
`tendermint_proto::types::ValidatorSet` <===> `tendermint::validator::Set`
`tendermint_proto::abci::ConsensusParams` <===> `tendermint::consensus::params::Params`

Required for https://github.com/informalsystems/ibc-rs/issues/277

### PR DESCRIPTION
**Pull request by greg-szabo**
Closes #634.

This is a research for #638 that adds Serialization support for protobuf structs.
 
* [X] Referenced an issue explaining the need for the change
* [ ] Updated all relevant documentation in docs
* [X] Updated all code comments where relevant
* [ ] Wrote tests
* [ ] Updated CHANGELOG.md

### CODE REVIEW

**Comment by greg-szabo** [comment]
All right, I think this research is a success. In this PR you can see the following:
* JSON serializers are moved into the tendermint-proto crate (`proto/src/serializers.rs` copied from tendermint) and hidden from the outside (serialization is a similar problem as protobuf encoding: noone cares, it just needs to work)
* protobuf types are annotated so all of them can be JSON serialized (https://github.com/informalsystems/tendermint-rs/blob/356324ac0f9ac663229db21ed212e3a402cfc85a/proto-compiler/build.rs#L23)
* custom serialization annotations are implemented in the proto-compiler crate in an easily expandable way (https://github.com/informalsystems/tendermint-rs/blob/356324ac0f9ac663229db21ed212e3a402cfc85a/proto-compiler/build.rs#L28) This is useful for fields that use some weird rule for serialization, for example serializing integers as strings.
* Finally, an example re-implementation of the AbciInfo type with the new serialization annotation (and as a domaintype on the side) shows how serialization is much less of a deal (https://github.com/informalsystems/tendermint-rs/blob/356324ac0f9ac663229db21ed212e3a402cfc85a/tendermint/tests/integration.rs#L69) This is implemented in a compact way in a test, so it can be compared with the old implementation. Obviously, these will go into the respective files, instead of tests.

If I get a "hey this works" from the team, I'll start revamping other types too, focusing on the types listed in #638 for IBC.

**Comment by greg-szabo** [comment]
I gave up on trying to organize JSON serialization for now. I've implemented a bunch of extra domain type conversions and moved a lot of the serialization into tendermint-proto, but we'll have to get back and do more structued thinking about JSON serialization.

I need to fix the light-client test failures and I'll implement the last domaintype conversion for Anca and wrap it up for review.

**Comment by greg-szabo** [comment]
The last test that fails is the model-based single-step tests. There were a few changes in the JSON encoding that doesn't seem to be in testgen. The most prominent one is that the "parts" field was renamed to "part_set_header" both in Go and in this branch in Rust but testgen still seem to generate "parts".

I've added time serialization annotation to some of the testgen tests where I saw it's having a hard time deserializing. 

Validator sets now contain a new "total_voting_power" field, but I think testgen doesn't generate that either.

I also found error messages missing "description" and "model" fields in the testgen structs but I don't know exactly what's missing there.

I'll need @andrey-kuprianov 's help to fix the remaining issues.

**Comment by ancazamfir** [comment]
Can we specify the revision to a commit hash in the proto-compiler?. Current ref used by gaia and go relayer stargate-4 release is:
```	github.com/tendermint/tendermint v0.34.0-rc4.0.20201005135527-d7d0ffea13c6```

**Comment by ancazamfir** [comment]
Missed this one:
We have some Merkle related structs here: https://github.com/informalsystems/tendermint-rs/blob/820b634e154d6dc1abe40bfa8f8e0c84ec272eb6/proto/src/prost/tendermint.crypto.rs#L34-L47
And similar here:
https://github.com/informalsystems/tendermint-rs/blob/820b634e154d6dc1abe40bfa8f8e0c84ec272eb6/tendermint/src/merkle/proof.rs#L9-L29

Could tendermint use the proto ones? Or impl the domain types? 
IBC gets the domain types from abci queries and needs to serialize into the protobuf ones.

**Review by thanethomson — APPROVED** [review]
So, a lot of work and thought and deliberation have gone into this PR and what the next steps from here should be. We're not yet where we need to be yet for v0.17.0, but I think it's important to at least push out a v0.17.0-rc2 release with the disclaimer that some more data structure changes are coming in v0.17.0-rc3. At the very least, rc2 will cater to IBC's immediate needs. Other consumers may want to wait until rc3 to upgrade.

The main thing that'd be good to fix right now before the v0.17.0-rc2 release is to get the Light Client's model-based single-step tests working with the new data structures introduced in this PR. cc @Shivani912 and @andrey-kuprianov 

I'm keeping this branch around for a bit until IBC can base off of v0.17.0-rc2 (or master).

**Comment by adizere** [comment]
FYI -- ibc-rs master no longer depends on branch `greg/research-json`, so it should be safe to delete from that perspective!

**Pull request merged**
