### PR TITLE
Fill in the `LightClientAttackEvidence` struct  and conversions to/from Protobuf

### PR DESCRIPTION
**Pull request by romac**
Closes: #1219

* [x] Referenced an issue explaining the need for the change
* [ ] Updated all relevant documentation in docs
* [ ] Updated all code comments where relevant
* [ ] Wrote tests
* [ ] Added entry in `.changelog/`

### CODE REVIEW

**Comment by ancazamfir** [comment]
Besides these changes I think we also need to put an API in place to be used by hermes. imho `tendermint-rs` should be filling in `Evidence::LightClientAttackEvidence` (e.g. the `byzantine_validators`) based on the two conflicting and maybe a common light block.
Also not clear to me if hermes will call the `broadcast_evidence()` RPC or we do this via the new API (call to `report_evidence()`?) and in the latter case if there are more changes required.

So maybe we need to work in parallel with the hermes PR here, you probably have better idea.

**Comment by romac** [comment]
> Besides these changes I think we also need to put an API in place to be used by hermes. imho tendermint-rs should be filling in Evidence::LightClientAttackEvidence (e.g. the byzantine_validators) based on the two conflicting and maybe a common light block.

Yes, I am working on that right now :)

**Comment by romac** [comment]
> Also not clear to me if hermes will call the broadcast_evidence() RPC or we do this via the new API (call to report_evidence()?) and in the latter case if there are more changes required.

What's this new API? Do you have a link to it?

Also should we keep submitting the `MisbehaviorEvidence` message to the chain like we do currently?

**Comment by ancazamfir** [comment]
> > Also not clear to me if hermes will call the broadcast_evidence() RPC or we do this via the new API (call to report_evidence()?) and in the latter case if there are more changes required.
> 
> What's this new API? Do you have a link to it?

the new API to be used by hermes to submit evidence to the node. 
> 
> Also should we keep submitting the `MisbehaviorEvidence` message to the chain like we do currently?
yes, that should stay.

**Comment by romac** [comment]
Superseded by #1260

**Pull request closed without merging**
