### PR TITLE
Update `k256` to v0.11 (fixes #1153) on v0.23.x

### LINKED ISSUE #1153: bump k256 to 0.11
Version(s) of tendermint-rs: v0.23.x

### What went wrong?

The old version blocks upgrading it in cosmrs: https://github.com/cosmos/cosmos-rust/pull/228#issuecomment-1127916960

### Steps to reproduce

create a crate that depends on tendermint-rs and tries to use the latest version of k256 at the same time (directly or via other dependencies) 

### Definition of "done"

a new version of v0.23 that upgraded the dependency

### PR DESCRIPTION
**Pull request by tomtau**
and relaxed the crate version bounds

* [x] Referenced an issue explaining the need for the change
* [N/A] Updated all relevant documentation in docs
* [N/A] Updated all code comments where relevant
* [N/A] Wrote tests
* [x] Added entry in `.changelog/`

### CODE REVIEW

**Comment by tomtau** [comment]
currently, it was only bumped on master: https://github.com/informalsystems/tendermint-rs/pull/1129 (i.e. v0.24.x)

**Comment by tony-iqlusion** [comment]
Not sure what's up with the clippy failure which looks unrelated.

This looks good to me and would unblock some TMKMS use cases as well.

**Review by tony-iqlusion — APPROVED** [review]

**Review by thanethomson — APPROVED** [review]

**Comment by thanethomson** [comment]
Yeah the clippy failure's totally unrelated, probably just due to new lints. I'll fix this in a follow-up.

```
error: `format!(..)` appended to existing `String`
  --> testgen/src/apalache.rs:70:13
   |
70 |             new_model += &format!("{} == ~{}\n", inv, test.test);
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `-D clippy::format-push-string` implied by `-D warnings`
   = help: consider using `write!` to avoid the extra allocation
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#format_push_string

error: could not compile `tendermint-testgen` due to previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `tendermint-testgen` due to previous error
```

**Comment by tony-iqlusion** [comment]
Thank you!

**Pull request merged**
