### PR TITLE
Source-based coverage

### PR DESCRIPTION
**Pull request by vitorenesduarte**
With this PR, we start tracking coverage using LLVM's source-based coverage: https://blog.rust-lang.org/inside-rust/2020/11/12/source-based-code-coverage.html

- pin nightly version to avoid spurious errors (it's unlikely we need to bump this often, unless we need new compiler features)
- pin grcov version to avoid https://github.com/mozilla/grcov/issues/555
- set `LLVM_PROFILE_FILE="%m.profraw"` to avoid overwrites of coverage data (which occur when several test binaries are run for the same crate): https://github.com/rust-lang/rust/issues/79899
  - maybe the 30% coverage decreases (https://github.com/informalsystems/tendermint-rs/pull/839#issuecomment-807115109 and https://github.com/informalsystems/tendermint-rs/issues/252#issuecomment-805623519) are due to something like this

With this, coverage is at 67.7%, which seems to be an all-time high 😄 

* [ ] Referenced an issue explaining the need for the change
* [ ] Updated all relevant documentation in docs
* [ ] Updated all code comments where relevant
* [ ] Wrote tests
* [ ] Updated CHANGELOG.md

### CODE REVIEW

**Review by thanethomson — APPROVED** [review]
Let's give this a try :+1: I'm looking forward to the results. Thanks @vitorenesduarte!

**Comment by romac** [comment]
Awesome, thanks a lot @vitorenesduarte !

**Comment by marco-c** [comment]
@vitorenesduarte could you try the latest version of grcov, with LLVM_PROFILE_FILE set to `%p-%m.profraw` instead of `%m.profraw`?

**Comment by vitorenesduarte** [comment]
> @vitorenesduarte could you try the latest version of grcov, with LLVM_PROFILE_FILE set to `%p-%m.profraw` instead of `%m.profraw`?

@marco-c trying it here: https://github.com/informalsystems/tendermint-rs/pull/864

**Pull request merged**
