### PR TITLE
Enable RPC integration tests in a new job on CI

### PR DESCRIPTION
**Pull request by greg-szabo**
I just realized that tendermint-rpc integration tests are not running in CI. This enables them.

* [ ] Referenced an issue explaining the need for the change
* [ ] Updated all relevant documentation in docs
* [ ] Updated all code comments where relevant
* [ ] Wrote tests
* [ ] Updated CHANGELOG.md

### CODE REVIEW

**Comment by greg-szabo** [comment]
Setting this to draft until the aminoff changes make it into master.

**Comment by greg-szabo** [comment]
An interesting question: one of the tests (block) fail because it receives an empty vector for merkle hash. Our implementation has the option to follow the RFC or use [0u8;32] as the interpretation of an empty vector. Or alternatively we can introduce an `Option<>` so `None` means the incoming hash string is empty.

What would be the correct approach?

**Comment by romac** [comment]
It seems to me that these tests are already executed in the `tendermint-rpc` job since they are not ignored.

**Comment by romac** [comment]
The tests in `tests/integration.rs` are more like conformance tests than integration tests since they do not run against a Tendermint node.

On the other hand, we have two tests which run against a node in:

```
test src/client/transport/http.rs - client::transport::http::HttpClient (line 17) ... ignored
test src/client/transport/websocket.rs - client::transport::websocket::WebSocketClient (line 72) ... ignored
```

**Comment by romac** [comment]
I pushed a commit that runs all ignored tests as part of the `tendermint-rpc-integration` job rather than only those in the `integration` test (of which they are none).

Perhaps we should rename that file/module/test to `conformance`?

**Comment by romac** [comment]
Just renamed it to `parse_response` which imho describes the tests better than `integration` or `conformance`.

**Review by romac — DISMISSED** [review]

**Review by romac — APPROVED** [review]

**Pull request merged**
