### PR TITLE
xla/multi-tc-versionsupport/fix

### PR DESCRIPTION
**Pull request by xla**
Addressing checks and warnings on the multi tc base branch.

### CODE REVIEW

**Comment by romac** [comment]
Hi @xla! Good to see you :) do you know what's up with the huge diff?

**Comment by xla** [comment]
@romac Hiiiiii. The issue is that I rebased main to pull in some of the fixes already applied there. Gonna look into it.

**Comment by xla** [comment]
> Hi @xla! Good to see you :) do you know what's up with the huge diff?

Addressed.

**Comment by romac** [comment]
Thank you :)

**Pull request merged**
