### PR TITLE
bump abci version in integration tests

### LINKED ISSUE #233: [ABCI]: catch up with 0.16.2 / 0.33.4
There seems to be a minor glitch in the integration tests:
```
failures:

---- rpc::abci_info stdout ----
thread 'rpc::abci_info' panicked at 'assertion failed: `(left == right)`
  left: `"0.16.2"`,
 right: `"0.16.1"`', tendermint/tests/integration.rs:37:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    rpc::abci_info

test result: FAILED. 9 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '-p tendermint --test integration'
##[error]The process '/usr/share/rust/.cargo/bin/cargo' failed with exit code 101
```

### PR DESCRIPTION
**Pull request by Liamsi**
Closes #233 

* [ ] Referenced an issue explaining the need for the change
* [ ] Updated all relevant documentation in docs
* [ ] Updated all code comments where relevant
* [ ] Wrote tests
* [ ] Updated CHANGES.md

### CODE REVIEW

**Comment by romac** [comment]
Looks good to me, seems to fix some previous test failures. It sounds like the `test-night-coverage` build is failing because latest Rust nightly yields a new warning about unnecessary braces which trigger an error because of `#![deny(warnings)]`.

I just tried running `cargo test --all-features` on latest nightly but it didn't yield any errors.
On the other hand, running `cargo clippy` on latest nightly yielded the following:

```
error: this import is redundant
 --> tendermint/src/rpc/endpoint/abci_info.rs:6:1
  |
6 | use serde_bytes;
  | ^^^^^^^^^^^^^^^^ help: remove it entirely
```

Maybe the former error is a false positive that was fixed in the latest nightly. The redundant import warning on the other hand seems legit and worth fixing.

**Comment by romac** [comment]
Apologies, I wasn't on the right branch. You indeed fixed the redundant warning I mentioned above.
Unfortunately I am unable to reproduce the `test-nightly-coverage` build error on my machine at the moment. I am getting some unrelated error about grcov and incremental builds.

**Comment by Liamsi** [comment]
> Unfortunately I am unable to reproduce the test-nightly-coverage build error on my machine at the moment.

Same here. Tried all sorts of things (crago clean, deleted the lock file, compared exact rustc version...) but couldn't reproduce locally.

**Comment by Liamsi** [comment]
@romac seemed to be a bug in nightly which was fixed after waiting a few nights. All tests pass now.

**Comment by Liamsi** [comment]
Looks like in the meantime abci version was updated to 0.17.0 :-D 
```
---- rpc::abci_info stdout ----
thread 'rpc::abci_info' panicked at 'assertion failed: `(left == right)`
  left: `"0.17.0"`,
 right: `"0.16.2"`', tendermint/tests/integration.rs:37:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Pull request merged**
