### PR TITLE
rpc: Fix deserialization of `/block_results` response when some tx results are non-ok

### PR DESCRIPTION
**Pull request by romac**
See https://github.com/informalsystems/hermes/issues/3817#issuecomment-1916478908 for background.

---

* [ ] Referenced an issue explaining the need for the change
* [ ] Updated all relevant documentation in docs
* [ ] Updated all code comments where relevant
* [ ] Wrote tests
* [ ] Added entry in `.changelog/`

### CODE REVIEW

**Comment by romac** [comment]
@mzabaluev We should probably do something smarter in cometbft-rs, eg. model `ExecTxResult` as an enum rather than have all successful and failing fields in the same struct.

**Comment by mzabaluev** [comment]
@romac
> We should probably do something smarter in cometbft-rs, eg. model `ExecTxResult` as an enum rather than have all successful and failing fields in the same struct.

Good idea. Which fields should be represented in results with `Code != 0`? I see "log" and "codespace" fields in these fixtures. What about "info"?

**Comment by romac** [comment]
Good question, I don't know! The fixture does not feature it in either case. Might have to check out the CometBFT source code to figure when it's included.

**Comment by mzabaluev** [comment]
Note that you can already match on the `abci::Code` domain type. As for whether the other fields may be present in `ExecTxResult` of a failed transaction, I can find no normative information on this. As far as I can see in the CometBFT source, result are only formed by test code, there are no helper methods to guide applications on how to properly report failures.

`codespace` perhaps only makes sense for non-zero codes and could be a member of redesigned `Code::Err`. `log` and `info` could be set with useful information in failure cases as well.
`gas_wanted`, `gas_used`, and `events` only make sense in the success case.

**Pull request merged**
