### PR TITLE
Reintroduce RPC query parsing

### LINKED ISSUE #859: Reintroduce query parsing for `tendermint-rpc`
#858 removed RPC query parsing to address #857. We should reintroduce it, but possibly look at replacing `rust-peg` with a different parser (e.g. `nom` or `LALRPOP`).

**What's the definition of "done" for this issue?**

Once we have reintroduced:
- [ ] RPC query parsing from arbitrary strings.
- [ ] Subscription functionality in the [`tendermint-rpc` CLI](https://github.com/informalsystems/tendermint-rs/tree/master/rpc/src/client/bin)

### PR DESCRIPTION
**Pull request by thanethomson**
Closes #859 

`rust-peg` had a release in April that solved some of the original issues we had with this. This PR is mostly just a copy/paste from #858.

* [x] Referenced an issue explaining the need for the change
* [x] Updated all relevant documentation in docs
* [x] Updated all code comments where relevant
* [x] Wrote tests
* [x] Added entry in `.changelog/`

### CODE REVIEW

**Comment by andynog** [comment]
Tested the subscribe with NewBlock events and seems to work correctly

**Review by xla — COMMENTED** [review]
utACK

✔️ 👛 🎿 ⛰

**Review by xla — APPROVED** [review]

**Comment by thanethomson** [comment]
Sorry @xla, had to fix a minor merge conflict. See https://github.com/informalsystems/tendermint-rs/pull/949/commits/8c5e9f6c11c8485f0483c33ae06e685880122e3e

**Review by xla — APPROVED** [review]
✨ ⏫ 🍽 💢

**Pull request merged**
