### PR TITLE
Release v0.38.0

### PR DESCRIPTION
**Pull request by ljoss17**

### CODE REVIEW

**Comment by tony-iqlusion** [comment]
Would it be possible to get an upgrade to `prost` v0.13 into this release? It's currently at `0.12`

**Comment by romac** [comment]
Yes, good idea!

**Comment by tony-iqlusion** [comment]
Opened a PR to bump `prost`/`tonic` here: https://github.com/informalsystems/tendermint-rs/pull/1444

**Comment by Farhad-Shabani** [comment]
From the perspective of `ibc-rs`, everything is fine as long as `ibc-proto-rs` can be properly upgraded with `prost` 0.13, since updates to `tendermint-proto` prompt corresponding updates in `ibc-proto-rs`.

**Comment by romac** [comment]
@Farhad-Shabani Here is the ibc-proto draft PR: https://github.com/cosmos/ibc-proto-rs/pull/223/

**Comment by romac** [comment]
@ljoss17 Now that https://github.com/informalsystems/tendermint-rs/pull/1444 is merged, can you please merge main and update the generated changelog?

**Review by Farhad-Shabani — APPROVED** [review]

**Pull request merged**
